final/final/ViewModels/WeekData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace final.ViewModels
{
    public class WeekData
    {
        public int Number {
            get;
            set;
        }

        public string NumberMessage{
            get;
            set;
        }
    }
}

final/final/Controllers/ExamController.cs
using final.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace final.Controllers
{
    public class ExamController : Controller
    {
        // GET: Exam
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.name = "劉紘維";
            ViewBag.number = "410603901";
            return View();
        }

        public ActionResult Week()
        {
            return View(new WeekData());
        }
        [HttpPost]
        public ActionResult Week(WeekData week)
        {
            if (week.Number == 1) {
                week.NumberMessage = "星期一";
            } else if (week.Number == 2) {
                week.NumberMessage = "星期二";
            } else if (week.Number == 3) {
                week.NumberMessage = "星期三";
            } else if (week.Number == 4) {
                week.NumberMessage = "星期四";
            } else if (week.Number == 5) {
                week.NumberMessage = "星期五";
            } else if (week.Number == 6) {
                week.NumberMessage = "星期六";
            } else if (week.Number == 7) {
                week.NumberMessage = "星期日";
            } else {
                week.NumberMessage = "錯誤輸入";
            }

            return View(week);
        }
    }
}

final/final/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace final.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

final/final/Views/Exam/About.cshtml
@{
    ViewBag.Title = "About";
}

@{
    string[] fruits = { "蘋果", "香蕉", "荔枝", "鳳梨", "西瓜" }; 
}

<div>
    @{
        <p>姓名: @ViewBag.name</p>
        <p>學號: @ViewBag.number</p>
        <p>喜歡的水果:</p>
        <ol>
            @foreach ( var item in fruits )
            {
                <li>@item</li>
            }
        </ol>
    }
</div>

final/final/Views/Exam/Week.cshtml
@model final.ViewModels.WeekData

@{
    ViewBag.Title = "Week";
}

<h2>Week</h2>

@using (Html.BeginForm("Week", "Exam", FormMethod.Post))
{
    <p>請輸入1~7:@Html.TextBoxFor(m => m.Number)</p>
    <p>查詢結果: @Model.NumberMessage</p>

    <input type="submit" value="顯示">
    
}

final/final/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

final/final/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

final/final/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

final/final/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("應用程式名稱", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                    <li>@Html.ActionLink("關於", "About", "Home")</li>
                    <li>@Html.ActionLink("連絡人", "Contact", "Home")</li>
                    <li>@Html.ActionLink("星期計算機", "Week", "Exam")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Date - 我的 ASP.NET 應用程式</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>